### ISSUE TITLE
rel_1这个咋来的呀，你们缝合REGAL模块的代码却感觉没缝合好，感觉好多地方都没说清楚。严重怀疑学术能力

### ISSUE THREAD

**Issue by caoguochao** [thecharm/Mega#17]

**Comment by thecharm** [comment]
你好，抱歉没有在README中详细说明，rel_1是structural alignment后的weights，你可以在dataset读取的代码中看到我们是如何将这个权重加入到模型中。关于这个权重的生成，我们提供了生成的流程，参见StructuralAlign文件夹下的具体说明，修改其中的文件路径（我们也提供了场景图的结构），你就可以得到这部分的权重代码。谢谢！如果有其他部分不清楚的，请具体列举下来～
