### ISSUE TITLE
模型ckpt的问题

### ISSUE THREAD

**Issue by laichengen** [thecharm/Mega#5]
你好，我下载的ckpt里面是MEGA_ckpt.tar压缩包，并不是ckpt，而且训练的话，效果好像达不到论文里面的准确率

**Comment by laichengen** [comment]
请问，可不可以提供一下推理用的ckpt呢

**Comment by thecharm** [comment]
> 

你好，我们提供的文件文件名错误，你可以简单的将文件名从"MEGA_ckpt.tar" 改为 “MEGA_ckpt.pth.tar” （这个不是压缩包，不需要解压，代码会自动读取）。即可运行inference.
或者，你可以重新执行inference 的命令（已更新到README.md文件）
